name: 'prepare-bareos-build'
description: 'Prepare Bareos app build file'
author: 'pyguy'
inputs:
  bareos_app:
    description: 'Bareos app name'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.bareos_app }}
